// Source list supplied for the Immunity catalog. Keep the catalog data separate
// from the workspace views so the proof workflow remains unchanged.
export const immunityThreats = [
  "0mega",
  "3PARA RAT",
  "4H RAT",
  "8Base",
  "AADInternals",
  "ABK",
  "Abyss Locker",
  "ACAD/Medre.A",
  "Accellion FTA SQL Injection (CVE-2021-27101)",
  "Access Token Theft",
  "Account Manipulation",
  "Account Takeover",
  "AcidPour",
  "AcidRain",
  "Action RAT",
  "Active Scanning",
  "Ad Fraud",
  "adbupd",
  "AdFind",
  "ADRecon",
  "Adups",
  "Adversary-in-the-Middle",
  "Adware Distribution",
  "Agenda Ransomware",
  "Agent Smith",
  "Agent Tesla",
  "Agent.btz",
  "AhRat",
  "Akira",
  "AlienBot",
  "ALPHV/BlackCat",
  "Ammyy Admin",
  "Amnesia:33",
  "Anatsa",
  "AndroRAT",
  "Anubis",
  "Apache Commons Text4Shell (CVE-2022-42889)",
  "Apache HTTP Server RCE (CVE-2021-42013)",
  "Apache Path Traversal (CVE-2021-41773)",
  "API Abuse",
  "AppleJeus",
  "Application Vulnerability Exploitation",
  "Application-Layer DDoS",
  "APT1",
  "APT28",
  "APT29",
  "APT3",
  "APT32",
  "APT33",
  "APT34",
  "APT35",
  "APT37",
  "APT38",
  "APT39",
  "APT40",
  "APT41",
  "APT42",
  "Arbitrary Code Execution",
  "Aria-body",
  "Arid Viper RAT",
  "Arkei",
  "ARP Spoofing",
  "AS-REP Roasting",
  "Asacub",
  "AsyncRAT",
  "Atlassian Bitbucket Command Injection (CVE-2022-36804)",
  "AtomSilo",
  "Attachment Phishing",
  "Authentication Bypass",
  "Authorization Bypass",
  "Autolycos",
  "Autorun Worm Propagation",
  "Avaddon",
  "Ave Maria",
  "AvosLocker",
  "AZORult",
  "BabLock",
  "Babuk",
  "BabyShark",
  "Back Orifice",
  "Back Orifice 2000",
  "Bad Rabbit",
  "BadBlock",
  "BadTunnel (CVE-2016-3213)",
  "BadUSB",
  "BadUSB Attack",
  "Bankshot",
  "Baron Samedit (CVE-2021-3156)",
  "Bashlite",
  "BeaverTail",
  "BGP Hijacking",
  "BianLian",
  "Bifrost",
  "BISCUIT",
  "BitPaymer",
  "Black Basta",
  "Black Basta Group",
  "BlackByte",
  "BlackCat Group",
  "BlackEnergy",
  "BlackHunt",
  "BlackMatter",
  "BlackMould",
  "BlackPOS",
  "Blackshades",
  "BlackSnake",
  "BlackStorm",
  "BlackSuit",
  "Blaster Worm",
  "BLASTPASS (CVE-2023-41064)",
  "BLINDINGCAN",
  "BloodHound Community Edition",
  "BlueBorne (CVE-2017-0781)",
  "BlueKeep (CVE-2019-0708)",
  "BlueSky Ransomware",
  "BONDUPDATER",
  "BOOSTWRITE",
  "Bootkit Installation",
  "Bootkit Persistence",
  "Borat RAT",
  "Botnet Recruitment",
  "Brain Cipher",
  "Bread",
  "Broadpwn (CVE-2017-9417)",
  "Broken Access Control",
  "Browser Credential Theft",
  "Browser Session Cookie Theft",
  "Browser-in-the-Browser Phishing",
  "Brute Force",
  "Brute Ratel C4",
  "BTCWare",
  "Buffer Overflow",
  "Bumblebee",
  "Bundlore",
  "Burp Suite",
  "Business Email Compromise",
  "BusyGasper",
  "Cable Haunt (CVE-2019-19494)",
  "Cannon",
  "Carbanak",
  "Carbanak Group",
  "Carbon",
  "CatB",
  "Cerber",
  "Cerberus Android",
  "Certify",
  "Certipy",
  "ChaChi",
  "Charming Kitten",
  "ChChes",
  "Checkm8",
  "Cheerscrypt",
  "Chimera",
  "China Chopper",
  "Chisel",
  "Chopstick",
  "Chrome Heap Buffer Overflow (CVE-2023-4863)",
  "Chrome Mojo Sandbox Escape (CVE-2020-16009)",
  "Chrome V8 Type Confusion (CVE-2021-21224)",
  "Chrome Zero-Day (CVE-2024-4671)",
  "Cisco ASA Path Traversal (CVE-2020-3452)",
  "Cisco IOS XE Web UI Implant (CVE-2023-20273)",
  "Cisco IOS XE Web UI Privilege Escalation (CVE-2023-20198)",
  "Cisco RV Router RCE (CVE-2022-20842)",
  "Cisco Smart Install RCE (CVE-2018-0171)",
  "Citrix ADC RCE (CVE-2019-19781)",
  "Citrix NetScaler RCE (CVE-2023-3519)",
  "CitrixBleed (CVE-2023-4966)",
  "Cleartext Transmission of Sensitive Information",
  "Click Fraud",
  "Clipboard Data Theft",
  "Cloak Ransomware",
  "Clop",
  "Clop Group",
  "Cloud Account Takeover",
  "Cloud Metadata Service Abuse",
  "Cobalt Strike",
  "Code Injection",
  "Code Injection Weakness",
  "Code Red",
  "Command Injection",
  "Command-and-Control over DNS",
  "Command-and-Control over HTTPS",
  "Command-and-Control over Web Services",
  "ComRAT",
  "Conficker",
  "Confluence Auth Bypass (CVE-2023-22515)",
  "Confluence Data Center RCE (CVE-2023-22527)",
  "Confluence OGNL Injection (CVE-2022-26134)",
  "Container Escape",
  "Conti",
  "Conti Group",
  "Cookie Missing HttpOnly Flag",
  "Cookie Missing SameSite Attribute",
  "Cookie Missing Secure Flag",
  "CookieMiner",
  "CORS Misconfiguration",
  "Covenant C2",
  "Cozy Bear",
  "CozyCar",
  "CrackMapExec",
  "Credential Dumping",
  "Credential Phishing",
  "Credential Stuffing",
  "Crimson",
  "CRLF Injection",
  "Crocodilus",
  "Cross-Site Request Forgery",
  "Cross-Site Request Forgery Weakness",
  "Cross-Site Scripting",
  "Cross-Site Scripting Weakness",
  "CrossRAT",
  "Crutch",
  "Cryakl",
  "CryLock",
  "Cryptojacking",
  "CryptoLocker",
  "CryptoShuffler",
  "CryptoWall",
  "CryptXXX",
  "Crysis",
  "CSP Misconfiguration",
  "Cuba Ransomware",
  "Cuckoo Stealer",
  "CurveBall (CVE-2020-0601)",
  "Cyclops Blink",
  "Dacls",
  "DanaBot",
  "DarkAngels",
  "DarkComet",
  "DarkGate",
  "DarkHotel",
  "DarkMoon",
  "DarkPower",
  "DarkSide",
  "DarkTortilla",
  "DarkVault",
  "DarkWatchman",
  "Data Destruction",
  "Data Exfiltration",
  "DCHSpy",
  "DCRAT",
  "DCShadow",
  "DCSync",
  "DeadBolt",
  "DEADEYE",
  "Deadlock",
  "DealersChoice",
  "DeathRansom",
  "Default Credentials",
  "DejaBlue (CVE-2019-1181)",
  "Dendroid",
  "Dependency Confusion",
  "Dependency on Vulnerable Component",
  "Derusbi",
  "Deserialization Attack",
  "Deserialization of Untrusted Data",
  "Dexter",
  "Dharma",
  "Diavol Loader",
  "Dipsind",
  "Directory Listing Enabled",
  "Dirty COW (CVE-2016-5195)",
  "Dirty Pipe (CVE-2022-0847)",
  "Disk Wipe",
  "Distributed Denial-of-Service",
  "DLL Search Order Hijacking",
  "DLL Side-Loading",
  "DNS Amplification",
  "DNS Hijacking",
  "DNS Spoofing",
  "DNS Tunneling",
  "DnsCat2",
  "Dok",
  "DOM-Based XSS",
  "Domain Generation Algorithm",
  "Domain Shadowing",
  "Domain Spoofing",
  "Donot Team RAT",
  "Donut Ransomware",
  "DoppelPaymer",
  "Double Extortion",
  "Double Free",
  "DoubleAgent",
  "Downfall (CVE-2022-40982)",
  "DownPaper",
  "DragonForce",
  "DragonForce Group",
  "DRATzarus",
  "Dridex",
  "Drive-by Compromise",
  "DROWN (CVE-2016-0800)",
  "Duqu",
  "Ebury",
  "ECCENTRICBANDWAGON",
  "Egregor",
  "EKANS",
  "Elbie",
  "Email Enumeration",
  "Email Spoofing",
  "Embargo Ransomware",
  "Emotet",
  "Empire Framework",
  "Encrypted Command Channel",
  "Enigma Ransomware",
  "Enmity",
  "Epsilon Red",
  "Equation Group",
  "EternalBlue (CVE-2017-0144)",
  "EternalRomance (CVE-2017-0145)",
  "Everest Ransomware",
  "Evil Corp",
  "Evil Twin Attack",
  "Evil-WinRM",
  "EvilBunny",
  "EvilGrab",
  "Exaramel",
  "Excessive Data Exposure",
  "Excessive IAM Permissions",
  "Exchange SSRF (CVE-2021-26855)",
  "Exfiltration over DNS",
  "Exfiltration over Web Service",
  "Exfiltration to Cloud Storage",
  "Exim RCE (CVE-2019-10149)",
  "Exim SMTP Smuggling (CVE-2023-51766)",
  "Exobot",
  "Exploit Public-Facing Application",
  "Exploitation for Client Execution",
  "Exposed Admin Interface",
  "Exposed Debug Endpoint",
  "Fake Software Update",
  "FakeM",
  "FakeSpy",
  "Fallout (CVE-2018-12126)",
  "Fancy Bear",
  "Fanny",
  "Fargo Ransomware",
  "Fast Reverse Proxy",
  "Felismus",
  "Ferret",
  "Fileless Malware Execution",
  "FIN7",
  "FIN8",
  "FinFisher",
  "Firefox IonMonkey Type Confusion (CVE-2019-11707)",
  "Firefox Sandbox Escape (CVE-2019-11708)",
  "Firmware Corruption",
  "FIVEHANDS",
  "Flame",
  "FlawedAmmyy",
  "FlawedGrace",
  "FluBot",
  "Follina (CVE-2022-30190)",
  "FONIX",
  "FORCEDENTRY (CVE-2021-30860)",
  "Foreshadow (CVE-2018-3615)",
  "Form Grabbing",
  "Format String Weakness",
  "FormBook",
  "Fortinet FortiManager Missing Authentication (CVE-2024-47575)",
  "Fortinet FortiOS Auth Bypass (CVE-2022-40684)",
  "FortiOS SSL-VPN Heap Overflow (CVE-2023-27997)",
  "Fortra FileCatalyst Workflow SQL Injection (CVE-2024-5276)",
  "Foudre",
  "FragAttacks",
  "FrameworkPOS",
  "FREAK (CVE-2015-0204)",
  "FruitFly",
  "Gamaredon Group",
  "Gamaredon Pterodo",
  "GameOver ZeuS",
  "GandCrab",
  "Gauss",
  "Gh0st RAT",
  "Ghostcat (CVE-2020-1938)",
  "GhostPack",
  "GhostRace (CVE-2024-2193)",
  "Ghostscript Sandbox Escape (CVE-2019-6116)",
  "GhostToken",
  "GhostWrite (CVE-2024-7344)",
  "Ginp",
  "GlanceLove",
  "GlobalProtect Portal RCE (CVE-2021-3064)",
  "Globe Ransomware",
  "GlobeImposter",
  "GoAnywhere MFT RCE (CVE-2023-0669)",
  "Golden Ticket",
  "GoldMax",
  "GoodWill Ransomware",
  "Goopy",
  "Gozi",
  "GPlayed",
  "Grandoreiro",
  "GratefulPOS",
  "GravityRAT",
  "Gustuff",
  "Hacking Team RCS",
  "Hades",
  "Hafnium",
  "Hafnium Exchange Exploit",
  "Hakuna Matata",
  "Hard-coded Cryptographic Key",
  "Hashcat",
  "Havij",
  "Havoc C2",
  "HawkEye",
  "Heap-Based Buffer Overflow",
  "Heartbleed (CVE-2014-0160)",
  "HelloKitty",
  "Helminth",
  "Hermes",
  "Hildegard",
  "Hive",
  "HiveNightmare (CVE-2021-36934)",
  "HolyGhost",
  "HOPLIGHT",
  "Horizontal Privilege Escalation",
  "Host Header Injection",
  "Hot Potato",
  "HotCroissant",
  "HTML Smuggling",
  "HTTP Request Smuggling",
  "HTTP Response Splitting",
  "HTTPBrowser",
  "HUI Loader",
  "HummingBad",
  "HummingWhale",
  "Hydraq",
  "HyperBro",
  "HyperStack",
  "IAM Role Abuse",
  "IceApple",
  "IcedID",
  "iKitten",
  "ILOVEYOU",
  "IMAPLoader",
  "Imminent Monitor",
  "Impacket",
  "Impacket GetUserSPNs",
  "Impacket PSExec",
  "Impacket SecretsDump",
  "Impacket SMBExec",
  "Impacket WMIExec",
  "Improper Access Control",
  "Improper Authentication",
  "Improper Cache Control",
  "Improper Certificate Validation",
  "Improper Error Handling",
  "Improper File Type Validation",
  "Improper Input Validation",
  "Improper Key Management",
  "Improper Neutralization of HTML",
  "Improper Neutralization of LDAP Queries",
  "Improper Neutralization of OS Command Elements",
  "Improper Neutralization of Script",
  "Improper Neutralization of SQL Elements",
  "Improper Neutralization of XML",
  "Improper Privilege Management",
  "Improper Session Expiration",
  "INC Ransomware",
  "Incorrect Authorization",
  "Incorrect Default Permissions",
  "Indrik Spider",
  "Industroyer",
  "Industroyer2",
  "Infinite Loop",
  "Inhibit System Recovery",
  "Insecure Cipher Suites",
  "Insecure Direct Object Reference",
  "Insecure Password Reset",
  "Insecure Temporary File",
  "Insecure Update Mechanism",
  "Insider Threat",
  "Instance Metadata SSRF",
  "Insufficient Entropy",
  "Integer Overflow or Wraparound",
  "Integer Underflow",
  "InvisibleFerret",
  "InvisiMole",
  "iOS BlastDoor",
  "Ivanti Connect Secure Auth Bypass (CVE-2023-46805)",
  "Ivanti Connect Secure Command Injection (CVE-2024-21887)",
  "Ivanti SSRF (CVE-2024-21893)",
  "JadeRAT",
  "Janus (CVE-2017-13156)",
  "Javali",
  "Jenkins CLI Arbitrary File Read (CVE-2024-23897)",
  "Jigsaw",
  "John the Ripper",
  "Joker Android",
  "JSSLoader",
  "JSWorm",
  "JWT Forgery",
  "Karakurt",
  "Kaseya VSA Auth Bypass (CVE-2021-30116)",
  "Kasseika",
  "Kazuar",
  "Kerberoasting",
  "Kerbrute",
  "KeyBoy",
  "Keylogging",
  "KillDisk Ransomware",
  "Kimsuky",
  "KINS",
  "Klez",
  "Knight Ransomware",
  "Koadic",
  "KONNI",
  "Kovter",
  "Koxic",
  "KRACK (CVE-2017-13077)",
  "Kronos",
  "Kubernetes API Abuse",
  "Kwampirs",
  "L1TF (CVE-2018-3646)",
  "LAPSUS$",
  "Lateral Movement",
  "Latrodectus",
  "LaZagne",
  "Lazarus Group",
  "Lazarus Manuscrypt",
  "LeChiffre",
  "LightNeuron",
  "LightSpy",
  "Ligolo-ng",
  "Lilith",
  "LinPEAS",
  "Living off the Land",
  "LNK File Abuse",
  "Local File Inclusion",
  "LockBit",
  "LockBit Group",
  "LockCrypt",
  "LockFile",
  "Locky",
  "LODEINFO",
  "Log4Shell (CVE-2021-44228)",
  "Lokibot",
  "LokiLocker",
  "LOLBin Abuse",
  "LookBack",
  "Looney Tunables (CVE-2023-4911)",
  "Lorenz",
  "LSASS Memory Dumping",
  "Lumma Stealer",
  "Machete",
  "MacMa",
  "MagicRAT",
  "Magniber",
  "Mahdi",
  "Makop",
  "Malicious File Execution",
  "Mallox",
  "Malvertising",
  "Man-in-the-Browser",
  "ManageEngine ADSelfService Plus RCE (CVE-2021-40539)",
  "ManageEngine ServiceDesk Plus RCE (CVE-2021-44077)",
  "Mandrake",
  "Mars Stealer",
  "Mass Assignment",
  "Masscan",
  "Matanbuchus",
  "Maui Ransomware",
  "MazarBOT",
  "Maze",
  "MDSUM (CVE-2019-11091)",
  "Medusa Android",
  "Medusa Brute Forcer",
  "Medusa Ransomware",
  "MedusaLocker",
  "MegaCortex",
  "MegaCortex Loader",
  "Melissa",
  "Meltdown (CVE-2017-5754)",
  "Memory Leak",
  "Merlin C2",
  "Mespinoza",
  "Metamorfo",
  "Metasploit Framework",
  "Meterpreter",
  "MFA Bypass",
  "MFA Fatigue",
  "Micropsia",
  "Microsoft Equation Editor RCE (CVE-2017-11882)",
  "Microsoft Office Memory Corruption (CVE-2017-0199)",
  "Microsoft Office MSDT RCE (CVE-2022-30190)",
  "Microsoft Outlook Moniker Link (CVE-2024-21413)",
  "Microsoft Outlook Privilege Escalation (CVE-2023-23397)",
  "Mimikatz",
  "Mindware",
  "Mirai",
  "MirrorStealer",
  "Mispadu",
  "Missing Account Lockout",
  "Missing Authentication for Critical Function",
  "Missing Authorization",
  "Missing Rate Limiting",
  "Missing Security Headers",
  "Moneybird",
  "Monokle",
  "MONTI",
  "MoonWind",
  "More_eggs",
  "Morris Worm",
  "MortalKombat",
  "Mosquito",
  "MountLocker",
  "MOVEit Transfer Auth Bypass (CVE-2023-35036)",
  "MoveIt Transfer SQL Injection (CVE-2023-34362)",
  "MuddyWater",
  "Mustang Panda",
  "Mydoom",
  "Mythic",
  "N-Day Exploit",
  "Name:Wreck",
  "NanoCore",
  "NavRAT",
  "Necurs",
  "Nefilim",
  "Nemty",
  "Nemucod",
  "NetBus",
  "Netcat",
  "NETEAGLE",
  "NetExec",
  "NetSupport RAT",
  "NetTraveler",
  "NetWalker",
  "NETWIRE",
  "NGLite",
  "Ngrok",
  "Night Sky",
  "Nimda",
  "njRAT",
  "NJRat Lime Edition",
  "Nmap",
  "NoEscape",
  "NOKKI",
  "Nokoyawa",
  "NotPetya",
  "NTLM Relay",
  "NTP Amplification",
  "Null Pointer Dereference",
  "OAuth Consent Phishing",
  "OAuth Token Theft",
  "OceanLotus",
  "Octopus",
  "Office Macro Execution",
  "OilRig",
  "OilRig OopsIE",
  "Olympic Destroyer",
  "OnionDuke",
  "Onyx Ransomware",
  "Open Cloud Storage Bucket",
  "Open Redirect",
  "Open Redirect Weakness",
  "OpenSSH Roaming Bug (CVE-2016-0777)",
  "OpenSSL Heartbleed",
  "OS Command Injection Weakness",
  "Oski Stealer",
  "OSX/Shlayer",
  "OSX_OCEANLOTUS.D",
  "Out-of-Bounds Read",
  "Out-of-Bounds Write",
  "Overprivileged Service Account",
  "OWASP ZAP",
  "P.A.S. Webshell",
  "P2P ZeuS",
  "Package Typosquatting",
  "Packet Sniffing",
  "PAN-OS Authentication Bypass (CVE-2025-0108)",
  "PAN-OS Command Injection (CVE-2024-3400)",
  "PaperCut NG Auth Bypass (CVE-2023-27350)",
  "Paradise Ransomware",
  "Pass the Hash",
  "Pass the Ticket",
  "Password Guessing",
  "Password Spraying",
  "Password Store Theft",
  "Path Traversal",
  "Path Traversal Weakness",
  "PEASS-ng",
  "Pegasus",
  "PetitPotam (CVE-2021-36942)",
  "Petya",
  "Phobos",
  "Pillowmint",
  "Play Ransomware",
  "PlugX",
  "PoisonIvy",
  "POODLE (CVE-2014-3566)",
  "PoshC2",
  "PowerLess",
  "PowerShell Abuse",
  "PowerShower",
  "PowerSploit",
  "PowerUp",
  "PowerView",
  "Predator the Thief",
  "Predictable Random Number Generator",
  "Predictable Session Identifier",
  "PrintNightmare (CVE-2021-34527)",
  "PrivescCheck",
  "Privilege Escalation",
  "Process Hollowing",
  "Process Injection",
  "Prolific Puma",
  "Prometheus Ransomware",
  "Prototype Pollution",
  "Proxy Command-and-Control",
  "ProxyLogon (CVE-2021-26855)",
  "ProxyNotShell (CVE-2022-41040)",
  "ProxyShell (CVE-2021-34473)",
  "PsExec",
  "Publicly Accessible Database",
  "Pulse Secure VPN RCE (CVE-2019-11510)",
  "Pupy",
  "PureCrypter",
  "Purple Fox",
  "PwnKit (CVE-2021-4034)",
  "PYSA",
  "QakBot",
  "Qbot",
  "Qilin",
  "QuadRooter",
  "Quantum Locker",
  "Race Condition",
  "Ragnar Locker",
  "RAMBleed (CVE-2019-0174)",
  "Ramnit",
  "RansomEXX",
  "RansomHouse",
  "RansomHub",
  "Ransomware Attack",
  "RedLine Stealer",
  "Reflected XSS",
  "Reflective DLL Injection",
  "Regin",
  "Registry Run Keys Persistence",
  "RegreSSHion (CVE-2024-6387)",
  "Regular Expression Denial of Service",
  "Remcos",
  "Remote Access Trojan Deployment",
  "Remote File Inclusion",
  "Removable Media Infection",
  "Responder",
  "Retbleed (CVE-2022-29900)",
  "Reuse of Initialization Vector",
  "Reuse of Nonce",
  "Revenge RAT",
  "REvil",
  "REvil Group",
  "Rhadamanthys",
  "Rhysida",
  "RIDL (CVE-2018-12127)",
  "Riltok",
  "Ripple20",
  "Ripple20 Treck TCP/IP",
  "Rising Sun",
  "RobbinHood",
  "Rogue Access Point",
  "RokRat",
  "Rook",
  "Rootkit Installation",
  "Rootkit Persistence",
  "Rotexy",
  "Rowhammer",
  "Royal Ransomware",
  "RTM",
  "Rubeus",
  "Ryuk",
  "Safari WebKit Use-After-Free (CVE-2023-28205)",
  "Sakula",
  "Salt Typhoon",
  "SaltySpider",
  "SambaCry (CVE-2017-7494)",
  "SamSam",
  "Sandbox Escape",
  "Sandworm Team",
  "Sasser",
  "Satori",
  "Sauron",
  "Scarab",
  "Scattered Spider",
  "Scheduled Task Persistence",
  "Screen Capture",
  "ScreenConnect Auth Bypass (CVE-2024-1709)",
  "ScreenConnect Path Traversal (CVE-2024-1708)",
  "Seatbelt",
  "Secrets in Environment Variables",
  "Secrets in Source Code",
  "Secrets Theft",
  "Security Account Manager Dumping",
  "Security Misconfiguration",
  "Sekhmet",
  "Sensitive Data in Logs",
  "Sensitive Data in URL",
  "SeriousSAM (CVE-2021-36934)",
  "Server-Side Request Forgery",
  "Server-Side Request Forgery Weakness",
  "Server-Side Template Injection",
  "ServHelper",
  "Service Account Token Theft",
  "Session Fixation",
  "Session Hijacking",
  "Session Token in URL",
  "Shade",
  "Shadow IT Exposure",
  "ShadowPad",
  "Shamoon",
  "SharpHound Collector",
  "SharpUp",
  "Shellshock (CVE-2014-6271)",
  "Shellshock Bash RCE",
  "Shlayer",
  "Sibot",
  "SideTwist",
  "Signed to Unsigned Conversion Error",
  "SIGRed (CVE-2020-1350)",
  "SilentTrinity",
  "Silver Ticket",
  "SIM Swapping",
  "Skeleton Key Attack",
  "Skidmap",
  "Sliver C2",
  "Slowloris",
  "SMB Relay",
  "SMBGhost (CVE-2020-0796)",
  "SmokeLoader",
  "Snake Keylogger",
  "SnakeStealer",
  "Snatch",
  "Sobig",
  "Socat",
  "SocGholish",
  "Sodinokibi",
  "Sofacy",
  "Software Supply Chain Compromise",
  "SolarWinds Serv-U RCE (CVE-2021-35211)",
  "SolarWinds Web Help Desk RCE (CVE-2024-28986)",
  "SombRAT",
  "Spearphishing Attachment",
  "Spearphishing Link",
  "Spearphishing Service",
  "Spectre Variant 1 (CVE-2017-5753)",
  "Spectre Variant 2 (CVE-2017-5715)",
  "Spora",
  "Spring4Shell (CVE-2022-22965)",
  "SpyAgent",
  "SpyNote",
  "Spyware Installation",
  "SQL Injection",
  "SQL Injection Weakness",
  "SQL Slammer",
  "sqlmap",
  "Stack-Based Buffer Overflow",
  "Stagefright (CVE-2015-1538)",
  "Stealth Mango",
  "Stolen Session Cookie",
  "STOP/Djvu",
  "Stored XSS",
  "Storm Worm",
  "Stormous",
  "StrandHogg",
  "StrifeWater",
  "StrongPity",
  "Struts2 RCE (CVE-2017-5638)",
  "Stuxnet",
  "sudo Baron Samedit",
  "SUNBURST",
  "SunCrypt",
  "SUNSPOT",
  "Supply Chain Attack",
  "SweynTooth",
  "SYN Flood",
  "SynAck",
  "SysUpdate",
  "T9000",
  "TA505",
  "TA551",
  "TA577",
  "Taidoor",
  "TAINTEDSCRIBE",
  "TAMECAT",
  "TangleBot",
  "TargetCompany",
  "TEARDROP",
  "Template Injection",
  "TERRACOTTA",
  "Terrapin Attack (CVE-2023-48795)",
  "TeslaCrypt",
  "Thanos",
  "THC Hydra",
  "ThreatNeedle",
  "Thunderclap",
  "Thunderspy",
  "TianySpy",
  "Time-of-Check Time-of-Use",
  "Tiny Banker Trojan",
  "TinyTurla",
  "Token Theft",
  "Tomiris",
  "Torisma",
  "Transparent Tribe",
  "Triada",
  "TrickBot",
  "Trident (CVE-2016-4655)",
  "Trigona",
  "Trojan Horse Delivery",
  "Turla Carbon",
  "Turla Group",
  "UDP Flood",
  "Uncontrolled Resource Consumption",
  "Unencrypted Backups",
  "Unpinned Dependency",
  "Unprotected API Keys",
  "Unrestricted File Upload",
  "Unsigned Software Update",
  "Urgent/11",
  "Ursnif",
  "USB Drop Attack",
  "Use After Free",
  "Use of Hard-coded Credentials",
  "User Execution",
  "Username Enumeration",
  "Valid Accounts Abuse",
  "Vawtrak",
  "Veeam Backup & Replication RCE (CVE-2023-27532)",
  "VegaLocker",
  "Verbose Error Messages",
  "Vertical Privilege Escalation",
  "Vice Society",
  "Vidar",
  "Virtual Machine Escape",
  "VMware Aria Operations Auth Bypass (CVE-2023-20887)",
  "VMware ESXi OpenSLP RCE (CVE-2021-21974)",
  "VMware Fusion Privilege Escalation (CVE-2023-20869)",
  "VMware Tools Authentication Bypass (CVE-2023-34058)",
  "VMware vCenter File Upload (CVE-2023-34048)",
  "VMware vCenter RCE (CVE-2021-21972)",
  "VMware Workspace ONE Access RCE (CVE-2022-22954)",
  "Voice Phishing",
  "VoidCrypt",
  "Volt Typhoon",
  "VPNFilter",
  "Vulnerability Scanning",
  "WannaCry",
  "WARPWIRE",
  "Watering Hole Attack",
  "Weak Cryptographic Algorithm",
  "Weak Password Requirements",
  "Weak TLS Configuration",
  "Weaponized Document",
  "Web Cache Deception",
  "Web Cache Poisoning",
  "Web Shell Deployment",
  "Web Shell Persistence",
  "WebKit Integer Overflow (CVE-2023-32409)",
  "WebP Heap Buffer Overflow (CVE-2023-4863)",
  "WellMess",
  "White Rabbit",
  "Wi-Fi Deauthentication",
  "Windows CLFS Privilege Escalation (CVE-2023-28252)",
  "Windows CryptoAPI Spoofing (CVE-2020-0601)",
  "Windows Installer Privilege Escalation (CVE-2021-41379)",
  "Windows TCP/IP RCE (CVE-2024-38063)",
  "WindTail",
  "Winnti",
  "Winnti Group",
  "WinPEAS",
  "WireLurker",
  "Wizard Spider",
  "WMI Abuse",
  "WolfRAT",
  "Woody RAT",
  "World-Writable File",
  "Worm Propagation",
  "X-Agent",
  "Xbash",
  "XcodeGhost",
  "XCSSET",
  "XingLocker",
  "XLoader",
  "XLoader Android",
  "XLoader iOS",
  "XML External Entity Injection",
  "XML External Entity Processing",
  "Yanluowang",
  "Zebrocy",
  "Zenbleed (CVE-2023-20593)",
  "Zeppelin",
  "Zero-Day Exploit",
  "ZeroAccess",
  "Zerologon (CVE-2020-1472)",
  "ZeuS",
  "Zeus Panda",
  "Zloader",
  "Zoho ManageEngine RCE (CVE-2022-47966)",
  "ZombieLoad (CVE-2018-12130)",
  "Zyklon",
] as const;
